### ISSUE TITLE
wasp_sensor.reload fails....

### ISSUE THREAD

**Issue by pointlevel** [dlashua/hass-wasp_sensor#6]
## Version of the custom_component
0.03

## Homeassistant logs

```yaml

[140145496937280] 'IntegrationConfigInfo' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 986, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 365, in async_handle_reload_all
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wasp_sensor/__init__.py", line 105, in reload_scripts_handler
    hass.data[DOMAIN] = conf[DOMAIN]
                        ~~~~^^^^^^^^
TypeError: 'IntegrationConfigInfo' object is not subscriptable

```

## Describe the bug
When doing a wasp_sensor.reload or homeassistant.reload_all, it fails with error " 'IntegrationConfigInfo' object is not subscriptable"
It only fails on reload, not a complete restart.

**Comment by pavan18125** [comment]
Same issue here. Did everything as mentioned in the blog and getting the same error.

**Comment by fourtrax01** [comment]
Same thing happening here as well. Is anyone even maintaining this it works great would hate to ditch it.
@pavan18125  what blog are you referring to?

**Comment by dlashua** [comment]
@fourtrax01 I am no longer maintaining this. PRs happily accepted.
